Make CI Pipeline more generic
openMSL/sl-1-0-sensor-model-repository-template pull request #29
Opened 2023-03-24 09:20 UTC by ClemensLinnhoff

**Add a description**
Currently, there are a couple of places in the CI pipeline that have to be adapted to a new model, when the template is used. This PR introduces an FMU_FILE_NAME variable in build pipeline, so only this variable has to be adapted when using the template. Everything else is now generic.

**Take this checklist as orientation for yourself, if this PR is ready for Maintainer Review**
- [x] My suggestion follows the [governance rules](https://github.com/openMSL/governance-and-documentation).
- [x] All commits of this PR are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] My changes generate no errors when passing CI tests. 
- [x] I updated all documentation (readmes incl. figures) according to my changes.
- [x] I have successfully implemented and tested my fix/feature locally.
- [x] Appropriate reviewer(s) are assigned.

2023-03-24 14:15 UTC, LukasElster requested changes

2023-03-24 14:15 UTC, LukasElster commented on README.md
> +To use the CI pipeline after clopying this template, you just have to change the file name of your model FMU (env: FMU_FILE_NAME) in [build.yml](.github/workflows/build.yml)>
Typo "clopying"

2023-03-24 15:14 UTC, ClemensLinnhoff commented on README.md
> +To use the CI pipeline after clopying this template, you just have to change the file name of your model FMU (env: FMU_FILE_NAME) in [build.yml](.github/workflows/build.yml)>
Good catch. Fixed it.

2023-03-25 18:40 UTC, LukasElster approved these changes

2023-03-26 08:55 UTC, merged